# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-09 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shandianbao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDBTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=64, unique=True, verbose_name='\u7ec8\u7aef\u53f7')),
                ('batch', models.CharField(max_length=64, verbose_name='\u6279\u6b21\u53f7')),
                ('company', models.CharField(max_length=64, verbose_name='\u673a\u5177\u5382\u5546')),
                ('pos_type', models.CharField(max_length=64, verbose_name='\u673a\u5177\u7c7b\u578b')),
                ('pos_version', models.CharField(max_length=64, verbose_name='\u673a\u5177\u578b\u53f7')),
                ('agent', models.CharField(max_length=64, verbose_name='\u4ee3\u7406\u5546\u53f7')),
                ('agent_name', models.CharField(max_length=64, verbose_name='\u4ee3\u7406\u7b80\u79f0')),
                ('bind_status', models.CharField(max_length=64, verbose_name='\u7ed1\u5b9a\u72b6\u6001')),
                ('activate_status', models.CharField(max_length=64, verbose_name='\u6fc0\u6d3b\u72b6\u6001')),
                ('bind_merchant', models.CharField(max_length=64, verbose_name='\u7ed1\u5b9a\u5546\u6237\u53f7')),
                ('bind_time', models.CharField(max_length=64, verbose_name='\u7ed1\u5b9a\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u722c\u53d6\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-terminal'],
                'db_table': 'sdb_terminal',
                'verbose_name': '\u7ec8\u7aef\u660e\u7ec6',
                'verbose_name_plural': '\u7ec8\u7aef\u660e\u7ec6',
            },
        ),
    ]
