# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SYFTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=64, verbose_name='\u6d3b\u52a8\u540d\u79f0')),
                ('merchant_receipt', models.CharField(max_length=64, verbose_name='\u5546\u6237\u53f7')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('agent_code', models.CharField(max_length=64, verbose_name='\u4ee3\u7406\u5546\u7f16\u53f7')),
                ('agent_name', models.CharField(max_length=64, verbose_name='\u6240\u5c5e\u4ee3\u7406\u5546')),
                ('sn_code', models.CharField(max_length=64, verbose_name='SN\u53f7')),
                ('terminal', models.CharField(max_length=64, unique=True, verbose_name='\u7ec8\u7aef\u53f7')),
                ('bind_date', models.CharField(max_length=64, verbose_name='\u7ed1\u5b9a\u65f6\u95f4')),
                ('recharge_date', models.CharField(max_length=64, verbose_name='\u5145\u503c\u65f6\u95f4')),
                ('recharge_status', models.CharField(max_length=64, verbose_name='\u5145\u503c\u72b6\u6001')),
                ('trade_rmb', models.CharField(max_length=64, verbose_name='\u6d3b\u52a8\u4ea4\u6613\u91d1\u989d\uff08\u5143\uff09')),
                ('ok_status', models.CharField(max_length=64, verbose_name='\u8fbe\u6807\u72b6\u6001')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u722c\u53d6\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'syf_terminal',
                'verbose_name': '\u6fc0\u6d3b\u5546\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u6fc0\u6d3b\u5546\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='SYFTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('merchant_receipt', models.CharField(max_length=64, verbose_name='\u5546\u6237\u540d\u79f0\u5c0f\u7968\u53f7')),
                ('settlement_type', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7ed3\u7b97\u7c7b\u578b')),
                ('account_type', models.CharField(max_length=64, verbose_name='\u5230\u8d26\u7c7b\u578b')),
                ('pay_status', models.CharField(max_length=64, verbose_name='\u4ee3\u4ed8\u72b6\u6001')),
                ('agent_code', models.CharField(max_length=64, verbose_name='\u4ee3\u7406\u5546\u7f16\u53f7')),
                ('agent_name', models.CharField(max_length=64, verbose_name='\u6240\u5c5e\u4ee3\u7406\u5546')),
                ('pos_type', models.CharField(max_length=64, verbose_name='POS\u673a\u7c7b\u578b')),
                ('yun', models.CharField(max_length=64, verbose_name='\u4e91\u95ea\u4ed8')),
                ('site_id', models.CharField(max_length=64, verbose_name='\u7f51\u5e97ID')),
                ('terminal', models.CharField(max_length=64, verbose_name='\u7ec8\u7aef\u53f7')),
                ('trade_date', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u65f6\u95f4')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('trade_type', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('consume_type', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('card_code', models.CharField(max_length=64, verbose_name='\u5361\u53f7')),
                ('card_type', models.CharField(max_length=64, verbose_name='\u6d88\u8d39\u5361\u7c7b\u578b')),
                ('trade_rmb', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u91d1\u989d\uff08\u5143\uff09')),
                ('trade_fee', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u624b\u7eed\u8d39\uff08\u5143\uff09')),
                ('trade_status', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('trade_card_type', models.CharField(max_length=64, verbose_name='\u5361\u7c7b\u578b')),
                ('auth_status', models.CharField(max_length=64, verbose_name='\u8ba4\u8bc1\u72b6\u6001')),
                ('card_bank', models.CharField(max_length=64, verbose_name='\u53d1\u5361\u884c')),
                ('return_code', models.CharField(max_length=64, verbose_name='\u8fd4\u56de\u7801')),
                ('return_info', models.CharField(max_length=64, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
                ('flow_status', models.CharField(max_length=64, verbose_name='\u6d41\u6c34\u72b6\u6001')),
            ],
            options={
                'db_table': 'syf_trade',
                'verbose_name': '\u4ea4\u6613\u660e\u7ec6',
                'verbose_name_plural': '\u4ea4\u6613\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='XYFToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'xyf_token',
                'verbose_name': '\u51ed\u8bc1',
                'verbose_name_plural': '\u51ed\u8bc1',
            },
        ),
    ]
