# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-21 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xyf', '0002_auto_20180407_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYFFenRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[(b'0.515', '0.515'), (b'0.520', '0.520'), (b'0.525', '0.525'), (b'0.530', '0.530'), (b'0.535', '0.535'), (b'0.540', '0.540'), (b'0.545', '0.545'), (b'0.550', '0.550')], max_length=50, verbose_name='\u63d0\u70b9')),
                ('message', models.TextField(blank=True, verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'xyf_fenrun',
                'verbose_name': '\u661f\u9a7f\u4ed8\u5206\u6da6',
                'verbose_name_plural': '\u661f\u9a7f\u4ed8\u5206\u6da6',
            },
        ),
        migrations.AlterModelOptions(
            name='xyfpos',
            options={'verbose_name': '\u7528\u6237POS\u673a', 'verbose_name_plural': '\u7528\u6237POS\u673a'},
        ),
    ]
