# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xyf', '0003_auto_20180421_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYFProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=64, verbose_name='\u7ec8\u7aef\u53f7')),
                ('trade_date', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u65f6\u95f4')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('trade_rmb', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u91d1\u989d\uff08\u5143\uff09')),
                ('trade_fee', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u624b\u7eed\u8d39\uff08\u5143\uff09')),
                ('trade_status', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('trade_card_type', models.CharField(max_length=64, verbose_name='\u5361\u7c7b\u578b')),
                ('return_code', models.CharField(max_length=64, verbose_name='\u8fd4\u56de\u7801')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5206\u7ea2\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'xyf_user_profit',
                'verbose_name': '\u661f\u7528\u6237\u83b7\u5229\u8868',
                'verbose_name_plural': '\u661f\u7528\u6237\u83b7\u5229\u8868',
            },
        ),
        migrations.CreateModel(
            name='XYFUserRMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmb', models.IntegerField(verbose_name='\u91d1\u989d(\u5206)')),
                ('child_rmb', models.IntegerField(default=0, verbose_name='\u63a8\u8350\u91d1\u989d(\u5206)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rmb', '-child_rmb'],
                'db_table': 'xyf_user_rmb',
                'verbose_name': '\u661f\u7528\u6237\u91d1\u94b1\u8868',
                'verbose_name_plural': '\u661f\u7528\u6237\u91d1\u94b1\u8868',
            },
        ),
    ]
