# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyf', '0004_xyfprofit_xyfuserrmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyfprofit',
            name='rmb',
            field=models.IntegerField(default=0, verbose_name='\u5229\u6da6\u91d1\u989d(\u5206)'),
        ),
    ]
