# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyf', '0005_xyfprofit_rmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyfprofit',
            name='fenrun_point',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u63d0\u70b9'),
        ),
    ]
