# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xyf', '0006_xyfprofit_fenrun_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYFTiXianOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(blank=True, max_length=512, verbose_name='\u7528\u6237\u8d26\u53f7')),
                ('rmb', models.IntegerField(verbose_name='\u63d0\u73b0\u91d1\u989d(\u5206)')),
                ('fee', models.IntegerField(verbose_name='\u63d0\u73b0\u624b\u7eed\u8d39(\u5206)')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='\u8ba2\u5355ID')),
                ('order_type', models.CharField(choices=[(b'RMB', '\u8fd4\u5229\u4f59\u989d\u63d0\u73b0'), (b'CHILD_RMB', '\u63a8\u8350\u4f59\u989d\u63d0\u73b0')], default=b'RMB', max_length=20, verbose_name='\u63d0\u73b0\u7c7b\u578b')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u63d0\u73b0\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u7ed3\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'xyf_tixian_order',
                'verbose_name': '\u661f\u63d0\u73b0\u8868',
                'verbose_name_plural': '\u661f\u63d0\u73b0\u8868',
            },
        ),
        migrations.AddField(
            model_name='xyfuserrmb',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='\u81ea\u52a8\u5230\u8d26'),
        ),
    ]
