# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HHJKMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=64, unique=True, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='\u5546\u6237\u540d\u79f0')),
                ('phone', models.CharField(max_length=64, verbose_name='\u624b\u673a')),
                ('agent_name', models.CharField(max_length=64, verbose_name='\u76f4\u5c5e\u673a\u6784')),
                ('merchant_type', models.CharField(max_length=64, verbose_name='\u5546\u6237\u7c7b\u578b')),
                ('create_time', models.CharField(max_length=64, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u722c\u53d6\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'hhjk_merchant',
                'verbose_name': '\u5546\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u5546\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='HHJKTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=64, verbose_name='\u5382\u5546')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('agent_code', models.CharField(max_length=64, verbose_name='\u673a\u6784\u7f16\u53f7')),
                ('pos_type', models.CharField(max_length=64, verbose_name='\u578b\u53f7')),
                ('terminal', models.CharField(max_length=64, verbose_name='\u7ec8\u7aef\u53f7')),
                ('communication', models.CharField(max_length=64, verbose_name='\u901a\u8baf\u65b9\u5f0f')),
                ('sn_code', models.CharField(max_length=64, unique=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('storage_date', models.CharField(max_length=64, verbose_name='\u5165\u5e93\u65f6\u95f4')),
                ('install_date', models.CharField(max_length=64, verbose_name='\u5b89\u88c5\u65f6\u95f4')),
                ('is_xjrw', models.CharField(max_length=64, verbose_name='\u643a\u673a\u5165\u7f51')),
                ('business', models.CharField(max_length=64, verbose_name='\u4e1a\u52a1\u6a21\u5f0f')),
                ('fee_receive', models.CharField(max_length=64, verbose_name='\u670d\u52a1\u8d39\u6536\u53d6')),
                ('fee_back', models.CharField(max_length=64, verbose_name='\u670d\u52a1\u8d39\u8fd4\u8fd8')),
                ('status', models.CharField(max_length=64, verbose_name='\u72b6\u6001')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u722c\u53d6\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-storage_date'],
                'db_table': 'hhjk_terminal',
                'verbose_name': '\u7ec8\u7aef\u8bbe\u5907',
                'verbose_name_plural': '\u7ec8\u7aef\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='HHJKToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'hhjk_token',
                'verbose_name': '\u51ed\u8bc1',
                'verbose_name_plural': '\u51ed\u8bc1',
            },
        ),
        migrations.CreateModel(
            name='HHJKTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('register_name', models.CharField(max_length=64, verbose_name='\u6ce8\u518c\u540d\u79f0')),
                ('agent_name', models.CharField(max_length=64, verbose_name='\u6240\u5c5e\u673a\u6784')),
                ('phone', models.CharField(max_length=64, verbose_name='\u624b\u673a')),
                ('terminal', models.CharField(max_length=64, verbose_name='\u7ec8\u7aef\u53f7')),
                ('trade_date', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u65e5\u671f')),
                ('trade_time', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u65f6\u95f4')),
                ('trade_rmb', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u91d1\u989d\uff08\u5143\uff09')),
                ('trade_type', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('trade_status', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('is_miao', models.CharField(max_length=64, verbose_name='\u662f\u5426\u79d2\u5230')),
                ('return_code', models.CharField(max_length=64, verbose_name='\u5e94\u7b54\u7801')),
                ('card_type', models.CharField(max_length=64, verbose_name='\u5361\u7c7b\u578b')),
                ('card_code', models.CharField(max_length=64, verbose_name='\u5361\u53f7')),
                ('card_bank', models.CharField(max_length=64, verbose_name='\u53d1\u5361\u884c')),
                ('trade_fee', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u624b\u7eed\u8d39\uff08\u5143\uff09')),
                ('qingfen_rmb', models.CharField(max_length=64, verbose_name='\u6e05\u5206\u91d1\u989d')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('fenrun', models.CharField(max_length=64, verbose_name='\u5206\u6da6')),
                ('trade_category', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u522b')),
                ('product', models.CharField(max_length=64, verbose_name='\u4ea7\u54c1\u6807\u8bc6')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u722c\u53d6\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-trade_date'],
                'db_table': 'hhjk_trade',
                'verbose_name': '\u4ea4\u6613\u660e\u7ec6',
                'verbose_name_plural': '\u4ea4\u6613\u660e\u7ec6',
            },
        ),
    ]
