# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinkong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JKToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7981\u7528')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'jk_token',
                'verbose_name': '\u51ed\u8bc1',
                'verbose_name_plural': '\u51ed\u8bc1',
            },
        ),
    ]
