# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinkong', '0003_auto_20180608_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='JKSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('register_name', models.CharField(max_length=64, verbose_name='\u6ce8\u518c\u540d\u79f0')),
                ('start_time', models.CharField(max_length=64, verbose_name='\u53d1\u8d77\u65f6\u95f4')),
                ('trade_rmb', models.CharField(max_length=64, verbose_name='\u91d1\u989d\uff08\u5143\uff09')),
                ('trade_fee', models.CharField(max_length=64, verbose_name='\u624b\u7eed\u8d39\uff08\u5143\uff09')),
                ('pay_type', models.CharField(max_length=64, verbose_name='\u4ed8\u6b3e\u65b9\u5f0f')),
                ('end_time', models.CharField(max_length=64, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('pay_status', models.CharField(max_length=64, verbose_name='\u7ed3\u7b97\u72b6\u6001')),
                ('fenrun', models.CharField(max_length=64, verbose_name='\u5206\u6da6')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u722c\u53d6\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-update_time'],
                'db_table': 'jk_settlement',
                'verbose_name': '\u4ea4\u6613\u660e\u7ec6',
                'verbose_name_plural': '\u4ea4\u6613\u660e\u7ec6',
            },
        ),
    ]
