# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jinkong', '0006_jkfenrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='JKYunFenRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[(b'0.28', '0.28'), (b'0.29', '0.29'), (b'0.30', '0.30'), (b'0.31', '0.31'), (b'0.32', '0.32'), (b'0.33', '0.33'), (b'0.34', '0.34'), (b'0.35', '0.35'), (b'0.36', '0.36'), (b'0.37', '0.37'), (b'0.38', '0.38')], max_length=50, verbose_name='\u63d0\u70b9')),
                ('message', models.TextField(blank=True, verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'jk_yunfenrun',
                'verbose_name': '\u91d1\u63a7\u4e91\u95ea\u4ed8\u5206\u6da6',
                'verbose_name_plural': '\u91d1\u63a7\u4e91\u95ea\u4ed8\u5206\u6da6',
            },
        ),
        migrations.AlterModelOptions(
            name='jkfenrun',
            options={'verbose_name': '\u91d1\u63a7\u5206\u6da6', 'verbose_name_plural': '\u91d1\u63a7\u5206\u6da6'},
        ),
    ]
