# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jinkong', '0007_auto_20180625_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='JKProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenrun_point', models.CharField(blank=True, max_length=50, verbose_name='\u63d0\u70b9')),
                ('rmb', models.IntegerField(default=0, verbose_name='\u5229\u6da6\u91d1\u989d(\u5206)')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u7f16\u53f7')),
                ('terminal', models.CharField(max_length=64, verbose_name='\u7ec8\u7aef\u53f7')),
                ('trade_date', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u65e5\u671f')),
                ('trade_rmb', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u91d1\u989d\uff08\u5143\uff09')),
                ('trade_status', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('return_code', models.CharField(max_length=64, verbose_name='\u5e94\u7b54\u7801')),
                ('card_type', models.CharField(max_length=64, verbose_name='\u5361\u7c7b\u578b')),
                ('trade_fee', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u624b\u7eed\u8d39\uff08\u5143\uff09')),
                ('qingfen_rmb', models.CharField(max_length=64, verbose_name='\u6e05\u5206\u91d1\u989d')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('fenrun', models.CharField(max_length=64, verbose_name='\u5206\u6da6')),
                ('trade_category', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u522b')),
                ('product', models.CharField(max_length=64, verbose_name='\u4ea7\u54c1\u6807\u8bc6')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5206\u7ea2\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'jk_user_profit',
                'verbose_name': '\u91d1\u7528\u6237\u83b7\u5229\u8868',
                'verbose_name_plural': '\u91d1\u7528\u6237\u83b7\u5229\u8868',
            },
        ),
        migrations.CreateModel(
            name='JKTiXianOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(blank=True, max_length=512, verbose_name='\u7528\u6237\u8d26\u53f7')),
                ('rmb', models.IntegerField(verbose_name='\u63d0\u73b0\u91d1\u989d(\u5206)')),
                ('fee', models.IntegerField(verbose_name='\u63d0\u73b0\u624b\u7eed\u8d39(\u5206)')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='\u8ba2\u5355ID')),
                ('order_type', models.CharField(choices=[(b'RMB', '\u8fd4\u5229\u4f59\u989d\u63d0\u73b0'), (b'CHILD_RMB', '\u63a8\u8350\u4f59\u989d\u63d0\u73b0')], default=b'RMB', max_length=20, verbose_name='\u63d0\u73b0\u7c7b\u578b')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u63d0\u73b0\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u7ed3\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'jk_tixian_order',
                'verbose_name': '\u91d1\u63d0\u73b0\u8868',
                'verbose_name_plural': '\u91d1\u63d0\u73b0\u8868',
            },
        ),
        migrations.CreateModel(
            name='JKUserRMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmb', models.IntegerField(verbose_name='\u91d1\u989d(\u5206)')),
                ('is_auto', models.BooleanField(default=False, verbose_name='\u81ea\u52a8\u5230\u8d26')),
                ('child_rmb', models.IntegerField(default=0, verbose_name='\u63a8\u8350\u91d1\u989d(\u5206)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rmb', '-child_rmb'],
                'db_table': 'jk_user_rmb',
                'verbose_name': '\u91d1\u7528\u6237\u91d1\u94b1\u8868',
                'verbose_name_plural': '\u91d1\u7528\u6237\u91d1\u94b1\u8868',
            },
        ),
    ]
