# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinkong', '0009_jkchildprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='jktrade',
            name='trade_fj_fee',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u4ea4\u6613\u9644\u52a0\u624b\u7eed\u8d39\uff08\u5143\uff09'),
        ),
        migrations.AlterField(
            model_name='jkfenrun',
            name='point',
            field=models.CharField(choices=[(b'0.500', '0.500'), (b'0.505', '0.505'), (b'0.510', '0.510'), (b'0.515', '0.515'), (b'0.520', '0.520'), (b'0.525', '0.525'), (b'0.530', '0.530'), (b'0.535', '0.535'), (b'0.540', '0.540'), (b'0.545', '0.545'), (b'0.550', '0.550'), (b'0.555', '0.555'), (b'0.560', '0.560'), (b'0.565', '0.565'), (b'0.570', '0.570'), (b'0.575', '0.575'), (b'0.580', '0.580'), (b'0.585', '0.585'), (b'0.590', '0.590'), (b'0.595', '0.595'), (b'0.60', '0.60')], max_length=50, verbose_name='\u63d0\u70b9'),
        ),
    ]
