# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='收件人')),
                ('phone', models.CharField(max_length=20, verbose_name='手机')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='座机')),
                ('area1', models.CharField(max_length=50, verbose_name='省')),
                ('area2', models.CharField(max_length=50, verbose_name='市')),
                ('area3', models.CharField(max_length=50, verbose_name='县')),
                ('address', models.CharField(max_length=250, verbose_name='具体地址')),
                ('post_code', models.CharField(blank=True, max_length=20, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='UserPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='POS序列号')),
                ('first_bound', models.BooleanField(default=False, verbose_name='是否第一次绑定')),
                ('is_activate', models.BooleanField(default=False, verbose_name='是否激活')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'user_pos',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('F', '女'), ('M', '男'), ('O', '其他')], max_length=1, verbose_name='性别')),
                ('is_vip', models.BooleanField(default=False, verbose_name='是否VIP')),
                ('code', models.CharField(max_length=36, unique=True, verbose_name='邀请码')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='上家')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('ya', '交押金'), ('tui', '退押金'), ('fen', '分红')], max_length=50, verbose_name='交易类型')),
                ('rmb', models.IntegerField(verbose_name='金额')),
                ('message', models.TextField(verbose_name='说明')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'user_trade',
            },
        ),
    ]
