# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFenRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[(b'5', '5'), (b'6', '6'), (b'7', '7'), (b'8', '8'), (b'9', '9')], max_length=50, verbose_name='\u63d0\u70b9')),
                ('rmb', models.CharField(choices=[(b'0.0', '0.0'), (b'0.1', '0.1'), (b'0.2', '0.2'), (b'0.3', '0.3'), (b'0.4', '0.4'), (b'0.5', '0.5'), (b'0.6', '0.6'), (b'0.7', '0.7'), (b'0.8', '0.8'), (b'0.9', '0.9'), (b'1.0', '1.0')], max_length=50, verbose_name='\u73b0\u91d1')),
                ('message', models.TextField(blank=True, verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_fenrun',
                'verbose_name': '\u7528\u6237\u5206\u6da6',
                'verbose_name_plural': '\u7528\u6237\u5206\u6da6',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_num',
            field=models.IntegerField(default=1, verbose_name='\u673a\u5668\u4e0a\u9650'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userpos',
            name='code',
            field=models.CharField(max_length=50, verbose_name='\u7ec8\u7aef\u53f7'),
        ),
    ]
