# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='\u4e0a\u5bb6'),
        ),
    ]
