# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180203_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpos',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfenrun',
            name='point',
            field=models.CharField(choices=[(b'5', '5'), (b'5.5', '5.5'), (b'6', '6'), (b'6.5', '6.5'), (b'7', '7'), (b'7.5', '7.5'), (b'8', '8'), (b'8.5', '8.5'), (b'9', '9'), (b'9.5', '9.5'), (b'10.0', '10.0')], max_length=50, verbose_name='\u63d0\u70b9'),
        ),
        migrations.AlterField(
            model_name='userfenrun',
            name='rmb',
            field=models.CharField(choices=[(b'0.0', '0.0'), (b'0.1', '0.1'), (b'0.2', '0.2'), (b'0.3', '0.3'), (b'0.4', '0.4'), (b'0.5', '0.5'), (b'0.6', '0.6'), (b'0.7', '0.7'), (b'0.8', '0.8'), (b'0.9', '0.9'), (b'1.0', '1.0')], max_length=50, verbose_name='\u79d2\u5230'),
        ),
    ]
