# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180204_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='LKLTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u53f7')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='\u5546\u6237\u6ce8\u518c\u540d\u79f0')),
                ('maintain', models.CharField(max_length=64, verbose_name='\u7ef4\u62a4\u65b9')),
                ('terminal', models.CharField(max_length=64, unique=True, verbose_name='\u7ec8\u7aef\u53f7')),
                ('category', models.CharField(max_length=64, verbose_name='\u4ea7\u54c1\u5206\u7c7b')),
                ('terminal_type', models.CharField(max_length=64, verbose_name='\u673a\u5177\u578b\u53f7')),
                ('open_date', models.CharField(max_length=64, verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('close_date', models.CharField(max_length=64, verbose_name='\u5173\u95ed\u65f6\u95f4')),
                ('is_give', models.CharField(max_length=64, verbose_name='\u662f\u5426\u8d60\u9001')),
                ('is_ok', models.CharField(max_length=64, verbose_name='\u662f\u5426\u8fbe\u6807')),
                ('ok_date', models.CharField(max_length=64, verbose_name='\u8fbe\u6807\u65f6\u95f4')),
            ],
            options={
                'db_table': 'lkl_terminal',
                'verbose_name': '\u7ec8\u7aef\u7ba1\u7406',
                'verbose_name_plural': '\u7ec8\u7aef\u7ba1\u7406',
            },
        ),
    ]
