# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_lklterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LKLD0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u53f7')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='\u5546\u6237\u6ce8\u518c\u540d\u79f0')),
                ('maintain', models.CharField(max_length=64, verbose_name='\u7b7e\u7ea6\u673a\u6784')),
                ('maintain_code', models.CharField(max_length=64, verbose_name='\u7b7e\u7ea6\u673a\u6784\u53f7')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('category', models.CharField(max_length=64, verbose_name='\u5206\u7c7b')),
                ('draw_date', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u65e5\u671f')),
                ('draw_rmb', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u91d1\u989d')),
                ('fee_rmb', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u624b\u7eed\u8d39')),
                ('real_rmb', models.CharField(max_length=64, verbose_name='\u5b9e\u9645\u6263\u6b3e')),
                ('trans_type', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('trans_status', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u72b6\u6001')),
            ],
            options={
                'db_table': 'lkl_d0',
                'verbose_name': '\u4ee3\u7406\u5546MPOS\u4e2a\u4ebaD0',
                'verbose_name_plural': '\u4ee3\u7406\u5546MPOS\u4e2a\u4ebaD0',
            },
        ),
        migrations.CreateModel(
            name='LKLD1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=64, verbose_name='\u5f53\u524d\u5e10\u53f7\u4e0b\u7ea7\u4ee3\u7406\u5546')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('maintain', models.CharField(max_length=64, verbose_name='\u7b7e\u7ea6\u673a\u6784')),
                ('maintain_code', models.CharField(max_length=64, verbose_name='\u7b7e\u7ea6\u673a\u6784\u53f7')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u53f7')),
                ('merchant_name', models.CharField(max_length=64, verbose_name='\u5546\u6237\u6ce8\u518c\u540d\u79f0')),
                ('terminal_num', models.CharField(max_length=64, verbose_name='\u7ec8\u7aef\u53f7')),
                ('draw_date', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u65e5\u671f')),
                ('draw_rmb', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u91d1\u989d')),
                ('fee_rmb', models.CharField(max_length=64, verbose_name='\u5546\u6237\u624b\u7eed\u8d39')),
                ('card_type', models.CharField(max_length=64, verbose_name='\u5361\u7c7b\u578b')),
                ('pay_date', models.CharField(max_length=64, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('pos_type', models.CharField(max_length=64, verbose_name='\u5361\u5e94\u7528\u7c7b\u578b')),
                ('terminal', models.CharField(max_length=64, verbose_name='PSAM\u5361\u53f7')),
            ],
            options={
                'db_table': 'lkl_d1',
                'verbose_name': 'MPOS\u4e2a\u4eba\u4ea4\u6613\u660e\u7ec6',
                'verbose_name_plural': 'MPOS\u4e2a\u4eba\u4ea4\u6613\u660e\u7ec6',
            },
        ),
    ]
