# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-21 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_lkld0_lkld1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitD0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('fenrun_point', models.CharField(max_length=50, verbose_name='\u63d0\u70b9')),
                ('fenrun_rmb', models.CharField(max_length=50, verbose_name='\u79d2\u5230')),
                ('rmb', models.IntegerField(verbose_name='\u5229\u6da6\u91d1\u989d(\u5206)')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u53f7')),
                ('draw_date', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u65e5\u671f')),
                ('draw_rmb', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u91d1\u989d')),
                ('fee_rmb', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u624b\u7eed\u8d39')),
                ('real_rmb', models.CharField(max_length=64, verbose_name='\u5b9e\u9645\u6263\u6b3e')),
                ('trans_type', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u7c7b\u578b')),
                ('trans_status', models.CharField(max_length=64, verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5206\u7ea2\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'user_profit_d0',
                'verbose_name': '\u7528\u6237D0\u83b7\u5229\u8868',
                'verbose_name_plural': '\u7528\u6237D0\u83b7\u5229\u8868',
            },
        ),
        migrations.CreateModel(
            name='ProfitD1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=64, unique=True, verbose_name='\u6d41\u6c34\u53f7')),
                ('fenrun_point', models.CharField(max_length=50, verbose_name='\u63d0\u70b9')),
                ('fenrun_rmb', models.CharField(max_length=50, verbose_name='\u79d2\u5230')),
                ('rmb', models.IntegerField(verbose_name='\u5229\u6da6\u91d1\u989d(\u5206)')),
                ('merchant_code', models.CharField(max_length=64, verbose_name='\u5546\u6237\u53f7')),
                ('draw_date', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u65e5\u671f')),
                ('draw_rmb', models.CharField(max_length=64, verbose_name='\u63d0\u6b3e\u91d1\u989d')),
                ('fee_rmb', models.CharField(max_length=64, verbose_name='\u5546\u6237\u624b\u7eed\u8d39')),
                ('card_type', models.CharField(max_length=64, verbose_name='\u5361\u7c7b\u578b')),
                ('pay_date', models.CharField(max_length=64, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('terminal', models.CharField(max_length=64, verbose_name='PSAM\u5361\u53f7')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5206\u7ea2\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'user_profit_d1',
                'verbose_name': '\u7528\u6237D1\u83b7\u5229\u8868',
                'verbose_name_plural': '\u7528\u6237D1\u83b7\u5229\u8868',
            },
        ),
        migrations.CreateModel(
            name='TiXianOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmb', models.IntegerField(verbose_name='\u63d0\u73b0\u91d1\u989d(\u5206)')),
                ('fee', models.IntegerField(verbose_name='\u63d0\u73b0\u624b\u7eed\u8d39(\u5206)')),
                ('status', models.CharField(choices=[(b'UP', '\u672a\u652f\u4ed8'), (b'PD', '\u5df2\u652f\u4ed8'), (b'SU', '\u6210\u529f')], default=b'UP', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='\u8ba2\u5355ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u63d0\u73b0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-pay_time'],
                'db_table': 'user_tixian_order',
                'verbose_name': '\u63d0\u73b0\u8868',
                'verbose_name_plural': '\u63d0\u73b0\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserRMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmb', models.IntegerField(verbose_name='\u91d1\u989d(\u5206)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_rmb',
                'verbose_name': '\u7528\u6237\u91d1\u94b1\u8868',
                'verbose_name_plural': '\u7528\u6237\u91d1\u94b1\u8868',
            },
        ),
        migrations.AlterField(
            model_name='userfenrun',
            name='rmb',
            field=models.CharField(choices=[(b'0.0', '0.0'), (b'0.1', '0.1'), (b'0.2', '0.2'), (b'0.3', '0.3'), (b'0.4', '0.4'), (b'0.5', '0.5'), (b'0.6', '0.6'), (b'0.7', '0.7'), (b'0.8', '0.8'), (b'0.9', '0.9'), (b'1.0', '1.0'), (b'1.1', '1.1'), (b'1.2', '1.2'), (b'1.3', '1.3'), (b'1.4', '1.4'), (b'1.5', '1.5')], max_length=50, verbose_name='\u79d2\u5230'),
        ),
        migrations.AlterField(
            model_name='userpos',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u7ec8\u7aef\u53f7'),
        ),
    ]
