# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userrmb_child_rmb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrmb',
            name='child_rmb',
            field=models.IntegerField(default=0, verbose_name='\u63a8\u8350\u91d1\u989d(\u5206)'),
        ),
    ]
