# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20180223_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlipay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='\u652f\u4ed8\u5b9d\u8d26\u6237')),
                ('name', models.CharField(max_length=50, verbose_name='\u652f\u4ed8\u5b9d\u5b9e\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_alipay',
                'verbose_name': '\u7528\u6237\u652f\u4ed8\u5b9d',
                'verbose_name_plural': '\u7528\u6237\u652f\u4ed8\u5b9d',
            },
        ),
    ]
