# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180304_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenrunorder',
            name='point',
            field=models.CharField(max_length=10, verbose_name='\u5206\u6da6\u70b9'),
        ),
        migrations.AlterField(
            model_name='fenrunorder',
            name='rmb',
            field=models.CharField(max_length=10, verbose_name='\u79d2\u5230\u70b9'),
        ),
    ]
