# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_childprofitd0_childprofitd1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childprofitd0',
            options={'ordering': ['-pay_time'], 'verbose_name': '\u63a8\u8350\u7528\u6237D0\u83b7\u5229\u8868', 'verbose_name_plural': '\u63a8\u8350\u7528\u6237D0\u83b7\u5229\u8868'},
        ),
        migrations.AlterModelOptions(
            name='childprofitd1',
            options={'ordering': ['-pay_time'], 'verbose_name': '\u63a8\u8350\u7528\u6237D1\u83b7\u5229\u8868', 'verbose_name_plural': '\u63a8\u8350\u7528\u6237D1\u83b7\u5229\u8868'},
        ),
        migrations.AddField(
            model_name='childprofitd0',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d0_father', to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u5e08'),
        ),
        migrations.AddField(
            model_name='childprofitd1',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d1_father', to=settings.AUTH_USER_MODEL, verbose_name='\u5bfc\u5e08'),
        ),
    ]
